name: Test Pull Request
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Use Node.js $
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Run tests
        run: npm test